default-scoreboard: "default"
show-scoreboard-on-join: true
scoreboards:
  default:
    title: "&bLOBBY"
    number-format:
      type: "fixed"
      value: "|"
    lines:
      - "&7Welcome {player}!"
      - "&fCoins: &6{objective.coins}"
  stats:
    title: "&e&lTEST"
    number-format:
      type: "blank"
    lines:
      - "&Name: {player}"
      - "&Health: {health}"
position-scoreboard:
  enabled: true
  prefix: "stalker_"
  scale:
    position: 1
    rotation: 1
    velocity: 100
  velocity:
    enabled: true